### PR TITLE
JOptionPane message added for now!

### PR DESCRIPTION
**Pull request by addressnopping**

### CODE REVIEW

**Review by IlNevioIl — APPROVED** [review]
This is actually the first time someone made a pull request for one of my projects lol

**Comment by IlNevioIl** [comment]
And ty for your work :)

**Comment by PeterPePem** [comment]
> This is actually the first time someone made a pull request for one of my projects lol

oh lol

**Comment by PeterPePem** [comment]
> And ty for your work :)

np :D

**Pull request merged**
